name: Deploy Website To Development

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket for production
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
      run:  |
        git config user.email "$GITHUB_ACTOR"
        git config user.name "$GITHUB_ACTOR"
        git remote set-url origin https://${{ secrets.GH_ACTION_TOKEN }}@github.com/southfact/southfact-gatsby-site.git
        npm install
        npm run build
        aws s3 sync ./public/ s3://dev.southfact.com --delete