# This workflow will do a clean install of node dependencies, build the source code and deploy to GH pages

name: Deploy to GH pages (development)

on:
  push:
    branches: [ gh-pages-dev ]
  pull_request:
    branches: [ gh-pages-dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy to GH Pages
      run: |
        git config user.email "$GITHUB_ACTOR"
        git config user.name "$GITHUB_ACTOR"
        git remote set-url origin https://${{ secrets.GH_ACTION_TOKEN }}@github.com/southfact/southfact-gatsby-site.git
        npm install
        npm run deploy
